trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.x.x'  
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildVersion: '17.0'
    msbuildArguments: '/p:Configuration=Release /p:Platform=Any CPU /p:OutputPath=$(Build.ArtifactStagingDirectory)'
    clean: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
